services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    _instanceof:
        Pipirima\PimcoreKeeperBundle\Factory\EventHandlerInterface:
            tags:
                - { name: pimcore_keeper.event_listener }
    Pipirima\PimcoreKeeperBundle\Factory\EventHandlerFactory:
        arguments: [!tagged pimcore_keeper.event_listener]

    Pipirima\PimcoreKeeperBundle\Service\MailerService: ~
    Pipirima\PimcoreKeeperBundle\Service\MailFactory: ~
    Pipirima\PimcoreKeeperBundle\Service\WebsiteSettingsService: ~
    Pipirima\PimcoreKeeperBundle\Service\ConfigService:
        arguments:
            - '%pimcore_keeper.alerts%'

    Pipirima\PimcoreKeeperBundle\EventListener\EventListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.class.preAdd }
            - { name: kernel.event_listener, event: pimcore.class.postAdd }
            - { name: kernel.event_listener, event: pimcore.class.preUpdate }
            - { name: kernel.event_listener, event: pimcore.class.postUpdate }
            - { name: kernel.event_listener, event: pimcore.class.preDelete }
            - { name: kernel.event_listener, event: pimcore.class.postDelete }

            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAddFailure }
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdateFailure }
            - { name: kernel.event_listener, event: pimcore.dataobject.deleteInfo }
            - { name: kernel.event_listener, event: pimcore.dataobject.preDelete }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDeleteFailure }
            - { name: kernel.event_listener, event: pimcore.dataobject.postCopy }
            - { name: kernel.event_listener, event: pimcore.dataobject.postCsvItemExport }

    Pipirima\PimcoreKeeperBundle\EventListener\ClassEventListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.class.preAdd }
            - { name: kernel.event_listener, event: pimcore.class.postAdd }
            - { name: kernel.event_listener, event: pimcore.class.preUpdate }
            - { name: kernel.event_listener, event: pimcore.class.postUpdate }
            - { name: kernel.event_listener, event: pimcore.class.preDelete }
            - { name: kernel.event_listener, event: pimcore.class.postDelete }
    Pipirima\PimcoreKeeperBundle\EventListener\DataObjectEventListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAddFailure }
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdateFailure }
            - { name: kernel.event_listener, event: pimcore.dataobject.deleteInfo }
            - { name: kernel.event_listener, event: pimcore.dataobject.preDelete }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDeleteFailure }
            - { name: kernel.event_listener, event: pimcore.dataobject.postCopy }
            - { name: kernel.event_listener, event: pimcore.dataobject.postCsvItemExport }
